/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthBridgeRouteImport } from './routes/auth.bridge'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedStudioIndexRouteImport } from './routes/_authenticated/studio.index'
import { Route as AuthenticatedStudioUploadRouteImport } from './routes/_authenticated/studio.upload'
import { Route as AuthenticatedStudioOnboardingRouteImport } from './routes/_authenticated/studio.onboarding'
import { Route as AuthenticatedStudioContentRouteImport } from './routes/_authenticated/studio.content'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthBridgeRoute = AuthBridgeRouteImport.update({
  id: '/bridge',
  path: '/bridge',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioIndexRoute =
  AuthenticatedStudioIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudioRoute,
  } as any)
const AuthenticatedStudioUploadRoute =
  AuthenticatedStudioUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => AuthenticatedStudioRoute,
  } as any)
const AuthenticatedStudioOnboardingRoute =
  AuthenticatedStudioOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedStudioRoute,
  } as any)
const AuthenticatedStudioContentRoute =
  AuthenticatedStudioContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedStudioRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/studio': typeof AuthenticatedStudioRouteWithChildren
  '/auth/bridge': typeof AuthBridgeRoute
  '/studio/content': typeof AuthenticatedStudioContentRoute
  '/studio/onboarding': typeof AuthenticatedStudioOnboardingRoute
  '/studio/upload': typeof AuthenticatedStudioUploadRoute
  '/studio/': typeof AuthenticatedStudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/bridge': typeof AuthBridgeRoute
  '/studio/content': typeof AuthenticatedStudioContentRoute
  '/studio/onboarding': typeof AuthenticatedStudioOnboardingRoute
  '/studio/upload': typeof AuthenticatedStudioUploadRoute
  '/studio': typeof AuthenticatedStudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/studio': typeof AuthenticatedStudioRouteWithChildren
  '/auth/bridge': typeof AuthBridgeRoute
  '/_authenticated/studio/content': typeof AuthenticatedStudioContentRoute
  '/_authenticated/studio/onboarding': typeof AuthenticatedStudioOnboardingRoute
  '/_authenticated/studio/upload': typeof AuthenticatedStudioUploadRoute
  '/_authenticated/studio/': typeof AuthenticatedStudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/studio'
    | '/auth/bridge'
    | '/studio/content'
    | '/studio/onboarding'
    | '/studio/upload'
    | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/bridge'
    | '/studio/content'
    | '/studio/onboarding'
    | '/studio/upload'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/studio'
    | '/auth/bridge'
    | '/_authenticated/studio/content'
    | '/_authenticated/studio/onboarding'
    | '/_authenticated/studio/upload'
    | '/_authenticated/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/bridge': {
      id: '/auth/bridge'
      path: '/bridge'
      fullPath: '/auth/bridge'
      preLoaderRoute: typeof AuthBridgeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/': {
      id: '/_authenticated/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof AuthenticatedStudioIndexRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
    '/_authenticated/studio/upload': {
      id: '/_authenticated/studio/upload'
      path: '/upload'
      fullPath: '/studio/upload'
      preLoaderRoute: typeof AuthenticatedStudioUploadRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
    '/_authenticated/studio/onboarding': {
      id: '/_authenticated/studio/onboarding'
      path: '/onboarding'
      fullPath: '/studio/onboarding'
      preLoaderRoute: typeof AuthenticatedStudioOnboardingRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
    '/_authenticated/studio/content': {
      id: '/_authenticated/studio/content'
      path: '/content'
      fullPath: '/studio/content'
      preLoaderRoute: typeof AuthenticatedStudioContentRouteImport
      parentRoute: typeof AuthenticatedStudioRoute
    }
  }
}

interface AuthenticatedStudioRouteChildren {
  AuthenticatedStudioContentRoute: typeof AuthenticatedStudioContentRoute
  AuthenticatedStudioOnboardingRoute: typeof AuthenticatedStudioOnboardingRoute
  AuthenticatedStudioUploadRoute: typeof AuthenticatedStudioUploadRoute
  AuthenticatedStudioIndexRoute: typeof AuthenticatedStudioIndexRoute
}

const AuthenticatedStudioRouteChildren: AuthenticatedStudioRouteChildren = {
  AuthenticatedStudioContentRoute: AuthenticatedStudioContentRoute,
  AuthenticatedStudioOnboardingRoute: AuthenticatedStudioOnboardingRoute,
  AuthenticatedStudioUploadRoute: AuthenticatedStudioUploadRoute,
  AuthenticatedStudioIndexRoute: AuthenticatedStudioIndexRoute,
}

const AuthenticatedStudioRouteWithChildren =
  AuthenticatedStudioRoute._addFileChildren(AuthenticatedStudioRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedStudioRoute: AuthenticatedStudioRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthBridgeRoute: typeof AuthBridgeRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthBridgeRoute: AuthBridgeRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
